spring:
  datasource:
    url: jdbc:mysql://101.42.90.74/aqi?useUnicode=true&characterEncoding=utf8
    username: aqi
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8001

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: static/*Mapper.xml